pipeline {
    agent any
    tools {nodejs "nodejs"}
    environment {
        build_mode = "stage" 
        finalArtifactName = "$GIT_BRANCH.$GIT_COMMIT.$BUILD_ID" + ".zip"
    }
    stages {

        stage('Versioning') {
            steps {
                sh 'printenv'
            }
        }       

        stage('Installing') {
            steps {
                echo 'Installation in progress..'
                sh 'npm install'
                echo 'Installation Finished'
            }
        }     

        stage('Lint') {
            steps {
                echo 'Linting in progress..'
                sh 'npm run lint'
                echo 'Linting Finished'
            }
        }    

        stage('Build') {
            steps {
                echo 'Building in progress..'
                sh 'npm run preBuild'
                sh "npm run build:${build_mode}"
                echo 'Building Finished'
            }
        }

        stage('Post Build') {
            steps {
                echo 'Post Building in progress..'
                sh 'npm run postBuild'
                echo 'Post Building Finished'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing in progress..'
                sh 'npm run test'
                echo 'Testing Finished'
            }
        }

        stage('Archiving') {
            steps {
                echo 'Archiving in progress..'
                sh """
                cd outputs
                zip -r -qq ${finalArtifactName}.${build_mode} dist/${build_mode}
                cd ..
                """
                echo 'Archiving Finished'
            }
        }        

    }
}
